version: '3'

vars:
  APP_NAME: nodejs-oidc-boilerplate
  DOCKER_HUB_PREFIX: docker.io/nightmanager
  DEV_REGISTRY: 192.168.0.175:5000
  KEYCLOAK_URL: http://keycloak.internal

tasks:
  keycloak-config:
    cmds:
    - cd ./deployment/dev/keycloak/ && KEYCLOAK_URL={{.KEYCLOAK_URL}} ./tf.sh apply
  keycloak-destroy-config:
    cmds:
    - cd ./deployment/dev/keycloak/ && KEYCLOAK_URL={{.KEYCLOAK_URL}} ./tf.sh destroy
  build-backend:
    cmds:
    - |
      cd backend
      npm run compile
      bun build --target node --external="$(jq -r '.dependencies|keys[]' package.json)" ./build/index.js --outfile ./dist/bundle.js
    sources:
    - backend/src/**/*
    generates:
    - backend/dist/bundle.js
  build-client:
    cmds:
    - |
      cd client
      npm run build
    sources:
    - client/src/**/*
    generates:
    - client/dist/**/*
  docker-backend:
    deps: [build-backend]
    cmds:
    - |
      docker_dir=deployment/docker/backend
      cp -a backend/dist/bundle.js $docker_dir/
      cp ./backend/package.json ./backend/package-lock.json $docker_dir/
      docker build -t {{.APP_NAME}}-backend $docker_dir
      docker tag {{.APP_NAME}}-backend {{.APP_NAME}}-backend:$APP_VERSION
  docker-client:
    deps: [build-client]
    cmds:
    - |
      docker_dir=deployment/docker/client
      rm -rf $docker_dir/index.html $docker_dir/assets
      cp -a client/dist/index.html client/dist/assets $docker_dir/
      cp ./client/package.json ./client/package-lock.json $docker_dir/
      docker build -t {{.APP_NAME}}-client $docker_dir
  # dev-registry-tag-push:
  #   deps: [docker-all]
  #   cmds:
  #   - |
  #     docker tag {{.APP_NAME}}-backend {{.DEV_REGISTRY}}/{{.APP_NAME}}-backend:$APP_VERSION
  #     docker push {{.DEV_REGISTRY}}/{{.APP_NAME}}-backend:$APP_VERSION
  #     docker tag {{.APP_NAME}}-cleint {{.DEV_REGISTRY}}/{{.APP_NAME}}-client:$APP_VERSION
  #     docker push {{.DEV_REGISTRY}}/{{.APP_NAME}}-client:$APP_VERSION
  docker-hub-tag-push-client:
    deps: [docker-client]
    cmds:
    - |
      docker tag {{.APP_NAME}}-client {{.DOCKER_HUB_PREFIX}}/{{.APP_NAME}}-client:$APP_VERSION
      docker push {{.DOCKER_HUB_PREFIX}}/{{.APP_NAME}}-client:$APP_VERSION
  docker-hub-tag-push-backend:
    deps: [docker-backend]
    cmds:
    - |
      docker tag {{.APP_NAME}}-backend {{.DOCKER_HUB_PREFIX}}/{{.APP_NAME}}-backend:$APP_VERSION
      docker push {{.DOCKER_HUB_PREFIX}}/{{.APP_NAME}}-backend:$APP_VERSION
  dev-deploy-client:
    deps: [docker-hub-tag-push-client]
    cmds:
    - |
        kubectl apply -f deployment/dev/app/client.yaml
        kubectl apply -f deployment/dev/app/httpproxy.yaml
        kubectl delete pod $(kubectl get pod -l app=nodejs-oidc-boilerplate-client -o jsonpath='{.items[0].metadata.name}')
  dev-deploy-backend:
    deps: [docker-hub-tag-push-backend]
    cmds:
    - |
        kubectl apply -f deployment/dev/app/backend.yaml
        kubectl apply -f deployment/dev/app/httpproxy.yaml
        kubectl delete pod $(kubectl get pod -l app=nodejs-oidc-boilerplate-backend -o jsonpath='{.items[0].metadata.name}')
  dev-deploy:
    deps: [docker-hub-tag-push-client, docker-hub-tag-push-backend]
    cmds:
    - |
      . ~/.nodejs-oidc-boilerplate.secrets
      kubectl delete secret nodejs-oidc-boilerplate-backend 2>/dev/null || echo "Error while deleting secret 'nodejs-oidc-boilerplate-backend', probably didn't exist yet. Creating it..."
      kubectl create secret generic nodejs-oidc-boilerplate-backend --from-literal=NODEJS_OIDC_BOILERPLATE_CLIENT_SECRET=$NODEJS_OIDC_BOILERPLATE_CLIENT_SECRET
      kubectl apply -f deployment/dev/app/backend.yaml
      kubectl apply -f deployment/dev/app/httpproxy.yaml
      kubectl delete pod $(kubectl get pod -l app=nodejs-oidc-boilerplate-backend -o jsonpath='{.items[0].metadata.name}')
  aws-client-to-s3:
    deps: [build-client]
    cmds:
    - |
      aws s3 cp --recursive client/dist s3://{{.APP_DOMAIN_NAME}}
  aws-tag-push-backend-to-ecr:
    deps: [docker-backend]
    cmds:
    - |
      . ${HOME}/.my-aws-config
      aws ecr get-login-password --profile $AWS_PROFILE --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      # aws --profile $AWS_PROFILE ecr create-repository --registry-id ${AWS_ACCOUNT_ID} --repository-name {{.APP_NAME}}-backend
      docker tag {{.APP_NAME}}-backend ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/{{.APP_NAME}}-backend:$APP_VERSION
      docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/{{.APP_NAME}}-backend:$APP_VERSION
  aws-deploy:
    cmds:
    - |
      . ${HOME}/.my-aws-config
      . ${HOME}/.nodejs-oidc-boilerplate.secrets
      cd deployment/aws/tf/cloudfront
      terragrunt run-all apply --terragrunt-include-external-dependencies
      # terragrunt apply
