apiVersion: v1
kind: Service
metadata:
  name: node-boilerplate-client
  labels:
    app: node-boilerplate-client
spec:
  selector:
    app: node-boilerplate-client
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-boilerplate-client
  name: node-boilerplate-client
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-boilerplate-client
  template:
    metadata:
      labels:
        app: node-boilerplate-client
    spec:
      containers:
      - image: nightmanager/node-boilerplate-client:0.0.1
        imagePullPolicy: Always
        name: node-boilerplate-client
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "1048Mi"
            cpu: "100m"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: node-boilerplate-client
        - name: client-config
          

